Allow dnf override conflicts by adding `--allowerasing` flag
to `dnf install`.

There's a failure in
https://github.com/stackrox/collector/pull/2157
https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs/pipelineruns/collector-on-push-mkgrn

The build log has this:

```
Error:
 Problem: package glibc-devel-2.28-251.el8_10.22.x86_64 from rhel-8-for-x86_64-baseos-rpms requires glibc = 2.28-251.el8_10.22, but none of the providers can be installed
  - package gcc-8.5.0-26.el8_10.x86_64 from rhel-8-for-x86_64-appstream-rpms requires glibc-devel >= 2.2.90-12, but none of the providers can be installed
  - cannot install both glibc-2.28-251.el8_10.22.x86_64 from rhel-8-for-x86_64-baseos-rpms and glibc-2.28-251.el8_10.16.x86_64 from @System
  - package gcc-c++-8.5.0-26.el8_10.x86_64 from rhel-8-for-x86_64-appstream-rpms requires gcc = 8.5.0-26.el8_10, but none of the providers can be installed
  - package glibc-minimal-langpack-2.28-251.el8_10.16.x86_64 from @System requires glibc = 2.28-251.el8_10.16, but none of the providers can be installed
  - conflicting requests
  - problem with installed package glibc-minimal-langpack-2.28-251.el8_10.16.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)
subprocess exited with status 1
subprocess exited with status 1
Error: building at STEP "RUN . /cachi2/cachi2.env &&     dnf -y install --nobest         make         wget         unzip         clang         llvm         cmake         gcc-c++         openssl-devel         ncurses-devel         curl-devel         libuuid-devel         libcap-ng-devel         autoconf         libtool         git         elfutils-libelf-devel         tbb-devel         c-ares-devel         patch         systemtap-sdt-devel &&     dnf -y clean all": exit status 1
```

The flag is described in `dnf --help` as:

```
--allowerasing        allow erasing of installed packages to resolve dependencies
```
see also https://dnf.readthedocs.io/en/latest/command_ref.html#options

We had it for a while in the downstream dockerfiles of main, added
when it got ported to P&Z, therefore I believe it should be safe to
have despite somewhat sparse documentation.